from scratchNNlib.Loss.Loss import Loss
from scratchNNlib.Loss.CategoricalCrossEntropy import CategoricalCrossEntropy
from scratchNNlib.Loss.MeanSquare import MeanSquare
from scratchNNlib.Loss.RootMeanSquare import RootMeanSquare